[context.production.environment]
  HUGO_VERSION = "0.55.4"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.4"

[build]
  command = "hugo --gc --minify --baseURL http://blacksalt.io --destination public --i18n-warnings --verbose"
  publish = "public/"
